# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches-ignore:
      - experimental/**
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - experimental/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [11]
        profile: [ '', '-Pclassic']

    steps:
      # Check out Git repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up environment with Java and Maven
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      # Build & Test
      - name: Build & Test with Maven
        run: mvn -s ./.maven-settings.xml -Pcontinuous-integration -B -U clean verify ${{ matrix.profile }}
